integration-e2e-updates
qua-platform/qualibrate-app pull request #116
Opened 2024-12-18 10:04 UTC by kleinwave

2025-01-14 09:58 UTC, nulinspiratie commented
@maxim-v4s could you help understand what's going wrong here? After qualibrate-config is settled

2025-01-15 08:06 UTC, nulinspiratie commented
@maxim-v4s has this been resolved with the latest qualibrate fix?

2025-01-15 08:12 UTC, maxim-v4s commented
> @maxim-v4s has this been resolved with the latest qualibrate fix?

@nulinspiratie yes, should be fixed.
But need to merge/rebase

2025-01-20 08:03 UTC, maxim-v4s requested changes

2025-01-20 08:03 UTC, maxim-v4s commented on .github/workflows/playwright-tests.yaml
> +          python-version: "3.10"
It should be useful to use cache for python installation
```yaml
steps:
- uses: actions/setup-python@v5
  with:
    python-version: '3.10'
    cache-dependency-path: |
      qualibrate-composite/poetry.lock
      qualibrate-app/backend/poetry.lock
      qualibrate-runner/poetry.lock
      qualibrate-core/poetry.lock
- name: Install qualibrate package
  run: |
    pip install 
    ./qualibrate
    ./qualibrate-app/backend
    ./qualibrate-runner
    ./qualibrate-core
```
This step should be located after copying static files

2025-01-23 06:55 UTC, maxim-v4s commented
@kleinwave 
Information for future
Review comments should be marked resolved only  by the one who it created or by the teamlead but not the one who created PR
There is a couple of comments that hasn't been fixed

2025-01-23 08:00 UTC, kleinwave commented
@maxim-v4s I see my bad I'll remember that moving forward. 
I just pushed again to resolve the other requested changes. 
Let me know if everything at this point looks good to merge.

2025-01-23 10:18 UTC, nulinspiratie approved these changes
Looks good to me! Nice job

2025-01-23 10:19 UTC, nulinspiratie commented
@maxim-v4s I've approved.
@kleinwave please implement the remaining comments from Maxim. After that, @maxim-v4s please review and merge if you're happy with it

2025-01-23 10:25 UTC, kleinwave commented on README.md
Implemented change [here](https://github.com/qua-platform/qualibrate-app/pull/116/commits/f7e307cf8a358ff984c6e3a88f03e9780a60aed0)

2025-01-23 10:33 UTC, maxim-v4s approved these changes

2025-01-23 10:34 UTC, merged